### ISSUE TITLE
Hey! 👋🏻 probably a dumb question

### ISSUE THREAD

**Issue by crisdosaygo** [ScottyFillups/p2pchat#25]
Hey Philip! 👋🏻 Nice work with Hyperbeam, btw! ❤️ 

Just on this, I'm super curious what the license is for this.

Just looks cool, understand if it's not important for you, question only! 😄

**Comment by philipjscott** [comment]
Hi Cris! Likewise, nice work with BrowserBox :slightly_smiling_face: 

It's a bit late for me but I'll make this MIT. Glad you like it.
